### PR TITLE
Bug 1240018 - Remove repos that cannot be cached

### PR DESCRIPTION
**Pull request by gregarndt**
These repos have issues with being cached so they should be removed from the list of cached repos that are submitted periodically.

### CODE REVIEW

**Comment by gregarndt** [comment]
Ok, travis is green, ok if I merge?

**Comment by gregarndt** [comment]
per bug 1238778, dolphin-512 is ok to remove.

**Comment by gregarndt** [comment]
Opened bug 1240018 to ask if these could be removed.

**Comment by selenamarie** [comment]
r+!

**Pull request merged**
