### PR TITLE
add npm-shrinkwrap.json

### PR DESCRIPTION
**Pull request by djmitche**
This should help support consistent installations of the tool even in the face of upgrades of dependent packages.

### CODE REVIEW

**Comment by jonasfj** [comment]
Oh, I would add the shrinkwrap to the place where the dockerfile lives... not to the actual package...

I guess one could do that, but I think shrinkwrap is intended for locking down deployments, not locking down packages on npm. Hmm maybe...because this isn't a lib but a binary... not sure what npm does when installing and shrinkwrap is in the package.

**Comment by jonasfj** [comment]
`r+` if you're sure this is where you want to put it..

On second thought If this works when it installs from npm it's probably a decent solution. Feel free to merge...

**Comment by djmitche** [comment]
From my understanding of the docs, this is correct.  It even works for a library, where the shrinkwrap file just defines that library's subtree of node_modules.

If I want to use this in the Dockerfile, I need to do a git clone of the tc-vcs repository at a particular revision, then install the shrinkwrap file in that repo, then run a bare `npm install -g`.  Upgrading means picking a different revision, using 'npm shrinkwrap' to generate a new shrinkwrap file, and installing that.  All of which suggests that's the wrong way to approach the problem.

What we ran into in this particular case was an older version of tc-vcs encountering some non-semver upgrade of some dependent package.  Upgrading tc-vcs fixed that.  In principle, there's no reason that couldn't happen with the most recently released version of tc-vcs, or any other npm executable or library.  *That* is the problem shrinkwrap fixes: when you make an npm release, you get to specify that your package should always be used with the dependency versions you tested.

**Comment by djmitche** [comment]
I'm not on the npm repo, though, so I can't make a new release of this.  Do you want to add me, or should I just wait for the next feature release?

**Pull request merged**
